analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - '**/build/**'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'
    - '**/*.setting.dart'

  errors:
    unnecessary_import: error
    unawaited_futures: error

linter:
  rules:
    always_use_package_imports: true
    avoid_classes_with_only_static_members: true
    avoid_types_on_closure_parameters: true
    avoid_returning_null: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    package_api_docs: true
    package_prefixed_library_names: true
    prefer_interpolation_to_compose_strings: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    test_types_in_equals: true
    throw_in_finally: true
    unawaited_futures: true
    unnecessary_lambdas: true
    unnecessary_statements: true
    use_super_parameters: true
    use_to_and_as_if_applicable: true
