name: rotation_log
repository: https://github.com/ueki-tomohiro/rotation_log
sdkPath: .fvm/flutter_sdk

packages:
  - packages/**

ignore:
  - "packages/**/*example"

command:
  version:
    linkToCommits: true
    branch: main
    workspaceChangelog: true

scripts:
  lint:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze: melos exec -- "dart analyze ."

  format: 
    run: fvm flutter format --fix packages
  
  test:
    exec: fvm flutter test
    packageFilters:
      dirExists:
        - test
      ignore:
        - "*example*"
  
  test-ci:
    exec: fvm flutter test --machine > test.json
    packageFilters:
      dirExists:
        - test
      ignore:
        - "*example*"

  combine: melos exec "\$MELOS_ROOT_PATH/scripts/combine_test.sh"