name: rotation_log
description: logging supported rotation files
version: 0.0.8
homepage: https://playon.jp
repository: https://github.com/ueki-tomohiro/rotation_log/tree/main/packages/rotation_log

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  archive: ^4.0.7
  meta: ^1.16.0
  clock: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.1
  stack_trace: ^1.12.1
  fake_async: ^1.3.3
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

