name: rotation_log
description: logging supported rotation files
version: 0.0.6
homepage: https://playon.jp
repository: https://github.com/ueki-tomohiro/rotation_log/tree/main/packages/rotation_log

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  archive: ^3.6.1
  meta: ^1.15.0
  clock: ^1.1.0
  intl: ^0.19.0
  path: ^1.9.0
  stack_trace: ^1.11.1
  fake_async: ^1.3.1
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
