name: rotation_log
description: Flutter logging helper with rotating files, structured logs, and ZIP export.
version: 0.1.1
homepage: https://playon.jp
repository: https://github.com/ueki-tomohiro/rotation_log/tree/main/packages/rotation_log

environment:
  sdk: '>=3.11.1 <4.0.0'
  flutter: ">=3.41.4"

dependencies:
  flutter:
    sdk: flutter
  clock: ^1.1.2
  archive: ^4.0.9
  fake_async: ^1.3.3
  intl: ^0.20.2
  logger: ^2.7.0
  meta: ^1.17.0
  path: ^1.9.1
  path_provider: ^2.1.5
  stack_trace: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
