name: rotation_log
description: logging supported rotation files
version: 0.0.3
homepage: https://playon.jp
repository: https://github.com/ueki-tomohiro/rotation_log/tree/main/packages/rotation_log

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9
  archive: ^3.3.0
  meta: ^1.7.0
  clock: ^1.1.0
  intl: ^0.17.0
  path: ^1.8.0
  stack_trace: ^1.10.0
  fake_async: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
