name: setup flutter
description: setup flutter
runs:
  using: "composite"
  steps:
    - name: setup java
      uses: actions/setup-java@v3
      with:
        java-version: "11"
        distribution: "adopt"
    - uses: dart-lang/setup-dart@v1
    - name: restore fvm cache
      uses: actions/cache@v3
      with:
        path: ~/fvm/versions
        key: ${{ runner.os }}-fvm-${{ hashFiles('.fvm/fvm_config.json') }}
        restore-keys: |
          ${{ runner.os }}-fvm-${{ hashFiles('.fvm/fvm_config.json') }}
          ${{ runner.os }}-fvm-
    - name: restore pubspec cache
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pubspec-${{ hashFiles('packages/app/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pubspec-${{ hashFiles('packages/app/pubspec.lock') }}
          ${{ runner.os }}-pubspec-
    - name: restore dart_tool
      uses: actions/cache@v3
      with:
        path: |
          packages/app/.dart_tool
        key: ${{ runner.os }}-dart-tool-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-dart-tool-${{ hashFiles('**/pubspec.lock') }}
          ${{ runner.os }}-dart-tool-
    - name: Install fvm
      run: |
        dart pub global activate fvm
        fvm install --verbose
      shell: bash
    - name: Install melos command
      run: dart pub global activate melos
      shell: bash
