name: lint

on:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/setup-flutter
      - name: flutter pub get
        run: melos run pub:get
      - name: flutter lint
        run: melos run lint

  unit_test:
    if: ${{ always() }}
    needs: lint
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/setup-flutter
      - name: flutter pub get
        run: melos run pub:get
      - name: flutter test
        run: melos run test-ci
      - name: flutter test combine
        run: melos run combine
        if: success() || failure()
      - uses: ueki-tomohiro/flutter-test-action@v1
        with:
          machinePath: report/test.json
        if: success() || failure()
